// Single permission catalog — mirrors MASTER section 11 and the backend
// security/permissions.py. Never inline permission strings elsewhere.
export const PERMISSIONS = [
  'organization.manage',
  'users.manage',
  'roles.manage',
  'integrations.manage',
  'audit.view',
  'projects.create',
  'projects.view',
  'projects.edit',
  'projects.archive',
  'projects.close',
  'people.view',
  'people.edit',
  'people.skills.manage',
  'people.availability.view',
  'people.availability.manage',
  'people.workload.view',
  'team.recommend',
  'team.assign',
  'team.remove',
  'team.override_capacity',
  'tickets.view',
  'tickets.create',
  'tickets.edit',
  'tickets.assign',
  'tickets.transition',
  'feedback.create',
  'feedback.view_shared',
  'feedback.view_private',
  'feedback.edit',
  'feedback.acknowledge',
  'reports.view',
  'reports.generate',
  'assistant.use',
  'assistant.propose_actions',
  'assistant.approve_actions',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
